models:
  - name: foo
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
  - name: bar
    columns:
      - name: id
        data_tests:
          - unique
          - not_null