version: 2

models:
  - name: foo
    
    config:
        contract:
            enforced: true

    columns:
      - name: id
        data_type: int
        data_tests:
          - relationships:
              to: ref('bar')
              field: id
        constraints:
          - type: foreign_key
            to: ref('bar')
            to_columns: [id]
        

  - name: bar
    
    config:
        contract:
            enforced: true
    columns:
      - name: id
        data_type: int
        constraints:
          - type: primary_key
            columns: [id]
        